Resources:
Ec2Instance:
 Type: 'AWS::EC2::Instance'
 Properties:
   SecurityGroups:
     - !Ref InstanceSecurityGroup
   KeyName: Mumbai_myudacity
   ImageId: 'ami-00bf4ae5a7909786c' # you may need to find out what instane types are available in your Rregion - use https://cloud-images.ubuntu.com/locator/ec2/
InstanceSecurityGroup:
 Type: 'AWS::EC2::SecurityGroup'
 Properties:
   GroupDescription: Enable SSH access via port 22
   SecurityGroupIngress:
     - IpProtocol: tcp
       FromPort: '22'
       ToPort: '22'
       CidrIp: 0.0.0.0/0